version: '3.4'

services:
  php:
    user: ${DOCKER_UID}
    restart: always
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
      target: php_fpm_dev
    volumes:
      - ./:/var/www/symfony:cached

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
